export enum OrderStatus {
  IN_CHECKOUT = 'IN_CHECKOUT',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_SECOND_PAYMENT = 'PENDING_SECOND_PAYMENT',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
